create table customer
(
	customer_id bigint GENERATED BY DEFAULT AS IDENTITY primary key,
	first_name varchar(100) not null,
	last_name varchar(100) not null,
	mobile_number varchar(100) not null,
	email varchar(100) unique not null
);

alter table customer
add column pan_card varchar(10) unique not null,
add column adhar_card varchar(12) unique not null,
add column date_of_birth date not null,
add column gender VARCHAR(10) CHECK (gender IN ('Male','Female','Other')) not null,
add column registration_date date default current_Date;

create table branch
(
	branch_id bigint generated by default as identity primary key,
	branch_name varchar(100) not null,
	ifsc_code varchar(11) unique not null,
	branch_address varchar(150) not null,
	city varchar(50) not null,
	state varchar(50) not null,
	branch_phone_number varchar(15) not null,
	manager_name varchar(100),
	created_at timestamp default current_timestamp
);

create table account
(
	account_id bigint generated by default as identity primary key,
	customer_id bigint not null,
	branch_id bigint not null,
	account_number bigint unique not null,
	account_type varchar(50) not null,
	balance numeric(15,2) not null,
	account_status varchar(20) not null,
	opening_date date default current_date not null,
	foreign key (customer_id) 
		references customer(customer_id),
	foreign key (branch_id) 
		references branch(branch_id)
);

create table employee
(
	employee_id int generated by default as identity primary key,
	branch_id bigint not null,
	first_name varchar(100) not null,
	last_name varchar(100) not null,
	designation varchar(100) not null,
	salary numeric(15,2) check(salary>=0) not null,
	hire_date date default current_date,
	email varchar(100) unique not null,
	mobile_number varchar(15) unique not null,
	foreign key (branch_id)
		references branch(branch_id)
	
);

CREATE TABLE loan
(
    loan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customer_id BIGINT NOT NULL,

    loan_type VARCHAR(20)
        CHECK (loan_type IN ('Home', 'Car', 'Personal'))
        NOT NULL,

    loan_amount NUMERIC(15,2)
        CHECK (loan_amount > 0)
        NOT NULL,

    interest_rate NUMERIC(5,2)
        CHECK (interest_rate > 0)
        NOT NULL,

    tenure_months INT
        CHECK (tenure_months > 0)
        NOT NULL,

    loan_status VARCHAR(20)
        CHECK (loan_status IN ('Active', 'Closed'))
        NOT NULL,

    approved_date DATE DEFAULT CURRENT_DATE NOT NULL,

    FOREIGN KEY (customer_id)
        REFERENCES customer(customer_id)
);

create table bank_transaction
(
	transaction_id bigint generated by default as identity primary key,
	account_id bigint not null,
	transaction_type VARCHAR(20) CHECK (transaction_type in ('Deposit','Withdrawal','Transfer')) NOT NULL,
	transaction_amount numeric(15,2) check(transaction_amount >= 0) not null,
	transaction_date date default current_date,
	transaction_status VARCHAR(20) CHECK (transaction_status IN ('Success','Pending','Failed')) NOT NULL, 
	remarks VARCHAR(255),  
	foreign key (account_id)
		references account(account_id)


);

create table card
(
	card_id bigint generated by default as identity primary key,
	account_id bigint not null,
	card_number varchar(16) unique not null,
	card_type varchar(100) not null,
	expiry_date date not null,
	cvv varchar(3) unique not null,
	card_status  VARCHAR(20) CHECK (card_status IN ('Active','Blocked','Expired')) NOT NULL,
	foreign key (account_id)
		references account(account_id)
	
);

create table beneficiary
(
	beneficiary_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	account_id bigint not null,
	beneficiary_name varchar(100) not null,
	beneficiary_account_number BIGINT NOT NULL,
	beneficiary_ifsc varchar(11) not null,
	created_at date default current_date,
	foreign key (account_id)
		references account(account_id)
);



SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';
